form_definitions = {
    "_first_name": "Ingresa tu Primer/Segundo nombre. Por ejemplo, 'Napoleón'.",
    "_last_name": "Escribe tu Primer/Segundo apellido. Por ejemplo, 'Bonaparte'.",
    "_email": "Proporciona tu dirección de correo electrónico. Por ejemplo, 'napoleon.bonaparte@mail.com'.",
    "_password": "Elige una contraseña segura. Por seguridad, esta entrada se muestra como puntos mientras la escribes.",
    "_address": "Ingresa tu dirección completa. Por ejemplo, 'Av. Conquista # 1804'.",
    "_phone_number": "Proporciona tu número de teléfono celular. Por ejemplo, '555-888-9999'.",
    "_dob": "Selecciona tu fecha de nacimiento.",
    "_gender": "Indica tu género. Por ejemplo, 'Masculino'.",
    "_nationality": "Ingresa tu nacionalidad. Por ejemplo, 'Francesa'.",
    "_id_user_type": "Selecciona el tipo de documento de identidad que posees.",
    "_id_user": "Ingresa tu número de documento de identidad sin puntos ni espacios.",
    "_is_ethnic": "Selecciona 'Sí' o 'No' según corresponda.",
    "_ethnic_affiliation": "Si seleccionaste 'Sí', elige la etnia a la que perteneces.",
    "_city_residence": "Ingresa la ciudad donde resides. Por ejemplo, 'París'.",
    "_guardian_fullname": "Proporciona el nombre completo de tu tutor legal.",
    "_guardian_relationship": "Indica tu relación con el tutor legal. Por ejemplo, 'Madre'.",
    "_guardian_id": "Ingresa el número de documento de identidad del tutor legal.",
    "_guardian_id_type": "Selecciona el tipo de documento de identidad del tutor legal.",
    "_emergency_phone": "Proporciona el número de teléfono del tutor o de contacto de emergencia.",
    "_education_level": "Selecciona tu nivel educativo actual.",
    "_topics_interest": "Selecciona los temas que te interesan. Puedes elegir más de uno.",
    "_disability": "Si tienes alguna discapacidad, selecciónala de la lista. Puedes elegir más de una si es necesario.",
    "_skills": "Selecciona las habilidades que posees. Puedes seleccionar más de una opción.",
    "_how_to_learn": "Elige cómo aprendes mejor. Selecciona las opciones que se ajusten a tu estilo de aprendizaje preferido.",
    "_weaknesses": "Selecciona las áreas en las que sientes que podrías mejorar o que representan desafíos para ti. No te preocupes, ¡todos tenemos áreas de mejora!",
    "_strengths": "Selecciona tus fortalezas. Estas son las áreas en las que te destacas y te sientes seguro. ¡Celebra tus puntos fuertes!",
    "_education_experience": "⚠️(Información Publica) Ingresa tu experiencia académica. Describe tu formación académica, títulos o certificaciónes",
    "_work_experience": "Ingresa tu experiencia laboral. Describe tu experiencia en general eso que no facil de lograr.",
    "_keywords_volunteer": "Selecciona las palabras que asocias con ser voluntario académico. Estas palabras reflejan tus motivaciones como voluntario."
}